// Generated by CoffeeScript 1.6.3
(function() {
  var capture, capturePage, openGweezyShot, screenshot, updateCookie;

  chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
    var send;
    console.log("M: " + request.msg + "T: " + request.type);
    switch (request.type) {
      case "snapshot":
        capture(sender.tab.id, request.dimensions);
        console.log("test");
    }
    sendResponse({});
    return send = function(request) {
      return chrome.tabs.sendMessage(sender.tab.id, request, function(response) {});
    };
  });

  chrome.extension.onRequest.addListener(function(request, sender, callback) {
    console.log("M: " + request.msg + "T: " + request.type);
    if (request.msg === 'capturePage') {
      console.log("Capture Page");
      return capturePage(request, sender, callback);
    } else {
      return console.error('Unknown message received from content script: ' + request.msg);
    }
  });

  chrome.browserAction.onClicked.addListener(function() {
    return chrome.tabs.getSelected(null, function(tab) {
      return openGweezyShot(tab);
    });
  });

  openGweezyShot = function(tab) {
    return chrome.tabs.captureVisibleTab(null, {
      format: "png"
    }, function(data) {
      chrome.storage.local.set({
        "screenshot": data
      });
      return console.log("img: " + data);
    });
  };

  updateCookie = function(url) {
    return chrome.cookies.set({
      "url": url,
      "name": "newpage",
      "value": "" + Math.floor((Math.random() * 1000000) + 1)
    });
  };

  screenshot = {};

  capturePage = function(data, sender, callback) {
    var canvas, scale;
    console.log("capturePage: " + data.x);
    scale = data.devicePixelRatio && data.devicePixelRatio !== 1 ? 1 / data.devicePixelRatio : 1;
    if (!screenshot.canvas) {
      canvas = document.createElement('canvas');
      canvas.width = data.totalWidth;
      canvas.height = data.totalHeight;
      screenshot.canvas = canvas;
      screenshot.ctx = canvas.getContext('2d');
      if (scale !== 1) {
        screenshot.ctx.scale(scale, scale);
      }
    }
    if (scale !== 1) {
      data.x = data.x / scale;
      data.y = data.y / scale;
    }
    return chrome.tabs.captureVisibleTab(null, {
      format: 'png',
      quality: 100
    }, function(dataURI) {
      var image;
      if (dataURI) {
        image = new Image();
        image.onload = function() {
          screenshot.ctx.drawImage(image, data.x, data.y);
          return callback(true);
        };
        return image.src = dataURI;
      }
    });
  };

  capture = function(tabId, dimensions) {
    var canvas, dataUrl, image;
    console.log("capture");
    dataUrl = screenshot.canvas.toDataURL();
    if (!canvas) {
      canvas = document.createElement("canvas");
      document.body.appendChild(canvas);
    }
    image = new Image();
    image.onload = function() {
      var context, croppedDataUrl;
      console.log("creating new image: " + window.devicePixelRatio);
      canvas.width = dimensions.width;
      canvas.height = dimensions.height;
      context = canvas.getContext("2d");
      context.drawImage(image, dimensions.left, dimensions.top, dimensions.width, dimensions.height, 0, 0, dimensions.width, dimensions.height);
      croppedDataUrl = canvas.toDataURL("image/png");
      chrome.tabs.sendMessage(tabId, {
        type: "export_done"
      }, function() {});
      return chrome.tabs.sendMessage(tabId, {
        type: "Gweezy_exportData",
        data: croppedDataUrl
      });
    };
    return image.src = dataUrl;
  };

}).call(this);
